inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "storage/**/*"
    - "log/**/*"
    - "lib/tasks/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "config/environments/*"
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"

Metrics/MethodLength:
  Max: 20

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

Layout/LineLength:
  Exclude:
    - "config/initializers/devise.rb"

Metrics/BlockLength:
  Exclude:
    - "config/environments/*"
